name: Check external data sources

on:
  workflow_dispatch:

jobs:
  check:
    outputs:
      diff: ${{ steps.diff.outputs.diff }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - id: diff
        name: Check sources
        env:
          TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
          TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
          TWITCH_USERNAME: ${{ secrets.TWITCH_USERNAME }}
          YT_API_KEY: ${{ secrets.YT_API_KEY }}
        run: |
          # compare API response with locally cached JSON data
          npm run build:ts

          if [[ $(npm run check) ]]; then
            echo "diff=0" >> "$GITHUB_OUTPUT"
            exit
          fi

          # data is different; rebuild the site
          echo "diff=1" >> "$GITHUB_OUTPUT"
          npm run build:11ty

  deploy:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.diff == '1'

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v2
