name: Check external data sources

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        ref: gh-pages

    - uses: actions/setup-node@v2
      with:
        node-version: 18.x
        cache: npm

    - name: Install dependencies
      run: npm install

    - name: Check sources
      env:
        TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
        TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
        TWITCH_USERNAME: ${{ secrets.TWITCH_USERNAME }}
        YT_API_KEY: ${{ secrets.YT_API_KEY }}
      run: |
        DIFF=0
        node tasks/checkTwitch.mjs || DIFF=1
        node tasks/checkYouTube.mjs || DIFF=1
        [ $DIFF == 0 ] && exit 0
        npx @11ty/eleventy
        git config user.email git@github.com
        git config user.name 'GitHub Actions'
        git add -f docs 11ty/data/external/*.json
        git commit -m 'external content update'
        git push -f -u origin gh-pages
