name: Publish site

on:
  push:
    branches: [main]

  workflow_dispatch:
    inputs:
      manual:
        default: "1"
        description: "Manual"

concurrency:
  group: publish

jobs:
  changes:
    name: Change detection
    runs-on: ubuntu-latest
    outputs:
      content: ${{ steps.changes.outputs.content }}
      engine: ${{ steps.changes.outputs.engine }}
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Detect changed files
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            changed:
              - "*.json"
              - ".eleventy.ts"
              - "11ty/**"
              - "content/**"
              - "data/**"
              - "static/**"
              - "tasks/**"

  build:
    needs: changes
    if: |
      github.event.inputs.manual != '' ||
      needs.changes.outputs.changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: haliphax/haliphax-dot-dev/.github@main

      - name: Build site
        env:
          TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
          TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
          TWITCH_USERNAME: ${{ secrets.TWITCH_USERNAME }}
          YT_API_KEY: ${{ secrets.YT_API_KEY }}
        run: npm run full

      - uses: actions/cache/save@v4
        with:
          key: external-data-${{ github.run_id }}
          path: 11ty/data/external

      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
