name: Publish site

on:
  push:
    branches: [main]

  workflow_dispatch:

concurrency:
  group: publish

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - uses: actions/cache/restore@v3
        with:
          key: external-data
          path: 11ty/data/external

      - name: Build site
        env:
          GH_TOKEN: ${{ github.token }}
          TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
          TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
          TWITCH_USERNAME: ${{ secrets.TWITCH_USERNAME }}
          YT_API_KEY: ${{ secrets.YT_API_KEY }}
        run: |
          # clear cache
          gh cache delete external-data || true

          #--- pull external data and build site
          npm run build:ts
          npm run check || true
          npm run build:11ty

      - uses: actions/cache/save@v3
        with:
          key: external-data
          path: 11ty/data/external

      - uses: actions/upload-pages-artifact@v2
        with:
          path: docs/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v2
