name: Publish site

on:

  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: 18.x
        cache: npm

    - name: Install dependencies
      run: npm install

    - name: Publish site
      env:
        TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
        TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
        TWITCH_USERNAME: ${{ secrets.TWITCH_USERNAME }}
        YT_API_KEY: ${{ secrets.YT_API_KEY }}
      run: |
        #--- pull external data ---#
        node tasks/checkTwitch.mjs || true
        node tasks/checkYouTube.mjs || true

        #--- build site ---#
        npx @11ty/eleventy

        #--- publish to GitHub Pages ---#
        git config user.email git@github.com
        git config user.name 'GitHub Actions'
        git add -f docs 11ty/data/external/*.json
        git commit -m 'publish site'
        git push -f -u origin master:gh-pages
