name: Publish site

on:

  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: npm

    - name: Install dependencies
      run: npm install

    - name: Publish site
      env:
        CNAME: ${{ secrets.CNAME }}
        TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
        TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
        TWITCH_USERNAME: ${{ secrets.TWITCH_USERNAME }}
      run: |
        mkdir docs
        echo "$CNAME" > docs/CNAME
        npx @11ty/eleventy
        git config user.email git@github.com
        git config user.name 'GitHub Actions'
        git add -f docs
        git commit -m 'publish site'
        git push -f -u origin master:gh-pages
