name: Streaming status
on:
  workflow_dispatch:
jobs:
  twitch-status:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: npm
    - name: Install dependencies
      run: npm install
    - name: Check and update status
      env:
        JSONBIN_TOKEN: ${{ secrets.JSONBIN_TOKEN }}
        JSONBIN_URL: ${{ secrets.JSONBIN_URL }}
        TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
        TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
        TWITCH_USERNAME: ${{ secrets.TWITCH_USERNAME }}
      run: npm run api
